version: "3.9"

services:
  bot:
    build: .
    image: telegram-yandex-bot:latest
    container_name: telegram-yandex-bot
    env_file:
      - .env
    environment:
      - OWNER_USER_ID=152423085
    volumes:
      - ./authorized_key.json:/app/authorized_key.json:ro
      - ./logs:/app/logs
      # SSL сертификаты не нужны - обрабатываются Hestia
    ports:
      - "11844:11844"  # Webhook порт для talkbot.skhlebnikov.ru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11844/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy для SSL терминации (ОТКЛЮЧЕН - у вас уже есть Hestia)
  # nginx:
  #   image: nginx:alpine
  #   container_name: telegram-bot-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - bot
  #   restart: unless-stopped
  #   profiles:
  #     - nginx  # Запускается только с профилем nginx